[phases.setup]
nixPkgs = ["nodejs"]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "node index.js"

[phases.setup]
nixPkgs = [
    "pkgs.cairo",
    "pkgs.pango",
    "pkgs.libjpeg",
    "pkgs.giflib",
    "pkgs.librsvg"
]
